spring.application.name=prod
bytemovr.bucket=bytemovr-files-prod
bytemovr.table=ByteMovrFiles
bytemovr.downloadTtlHours=24
bytemovr.downloadsAllowed=1

server.port=8080

# CORS for dev (you can tighten later)
spring.web.cors.allowed-origins=*
spring.web.cors.allowed-methods=GET,POST,OPTIONS
spring.web.cors.allowed-headers=*
spring.web.cors.allow-credentials=true
